import React, { useState, useEffect,useContext } from "react";
import style from '../../styles/detailProd.module.css'
import { useRouter } from "next/router";
import ViewCars from "@/component/viewCars";
import Sidebar from "@/component/sidebar";
import Navbar from "@/component/navbar";
import Head from 'next/head'
import Divider from '@mui/material/Divider';
import Slider from "@/component/carousel";
import {CgMenuGridO} from 'react-icons/cg'
import {RiMessengerFill} from "react-icons/ri"
import Profil from '../../public/profile.jpg'
import Image from 'next/image'
import {FaGamepad,FaBell} from 'react-icons/fa'
import useMediaQuery from '@mui/material/useMediaQuery';
import SideDetailProd from "@/component/sideDetailProd";
import LZString from 'lz-string';

export default function DetailProd() {
    const matches = useMediaQuery('(max-width:900px)');
    const router = useRouter();
    const { id } = router.query;
    const [prod, setProd] = useState('');
   
  useEffect(() => {
    const storedData = localStorage.getItem('prod');
    if (storedData) {
      const decompressedData = LZString.decompress(storedData);
      const parsedData = JSON.parse(decompressedData);
      const item =parsedData.find((item) => item.id === id);
      // Use parsedData to retrieve the desired item...
      setProd(item)
    }
  }, [id]);

  console.log(prod);
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    <div className={style.detail}>
       <Navbar show='false' bgColor={!matches} iconSearch='false'/>
       <div className={style.detailProd} >
       <Slider location={prod.location} image={prod.images}/> 
       <SideDetailProd id={prod.id} title={prod.title} location={prod.location} price={prod.price} condition={prod.condition} disc={prod.disc}/>
    </div>
    </div>
    </>
  )
}
