import React, { useState, useEffect,useContext } from "react";
import style from '../../styles/detailProd.module.css'
import { useRouter } from "next/router";
import ViewCars from "@/component/viewCars";
import Sidebar from "@/component/sidebar";
import Head from 'next/head'
import Divider from '@mui/material/Divider';
import Slider from "@/component/carousel";
import {CgMenuGridO} from 'react-icons/cg'
import {RiMessengerFill} from "react-icons/ri"
import Profil from '../../public/profile.jpg'
import Image from 'next/image'
import {FaGamepad,FaBell} from 'react-icons/fa'
import SideDetailProd from "@/component/sideDetailProd";


export default function DetailProd() {
    const router = useRouter();
  const { id } = router.query;
  const [prod, setProd] = useState([]);

  useEffect(() => {
    const storedProd = JSON.parse(localStorage.getItem('prod'));
    const product = storedProd.find((product) => product.id === id);
    setProd(product);
  }, [id]);



console.log(prod);
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
    <div className={style.detailProd} >
     <Slider location={prod.location}/> 
     <SideDetailProd />
    </div>
    </>
  )
}
