import React from 'react'
import style from '../styles/car.module.css'
import Head from 'next/head'
import SidebarCars from '@/component/SidebarCars'
import ViewCars from '@/component/viewCars'

export default function Car() {
  
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={style.car}>
        <SidebarCars />
        <ViewCars />
      </div>
    </>
  )
}
