import React from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../component/navbar'
import Sidebar from '../component/sidebar'
import Store from '../component/content'
import {SiFacebook} from 'react-icons/si'


export default function Home() {
  return (
    <>
      <Head>
        <title>Marketplace</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.marketplace}>
        <Navbar iconCancel='false'/>
        <div className={styles.home}>
          <Sidebar />
          <Store />
        </div>
      </div>
    </>
  )
}
